export const USER_INFO_RETRIEVE_START = "USER_INFO_RETRIEVE_START";
export const USER_INFO_RETRIEVE_COMPLETE = "USER_INFO_RETRIEVE_COMPLETE";
export const CREATE_ITINERARY_START = "CREATE_ITINERARY_START";
